environment:
  matrix:
    # For Python versions available on Appveyor, see
    # https://www.appveyor.com/docs/windows-images-software/#python
    # The list here is complete (excluding Python 2.6, which
    # isn't covered by this document) at the time of writing.

    - PYTHON: "C:\\Python39-x64"
    - PYTHON: "C:\\Python310-x64"
    - PYTHON: "C:\\Python311-x64"
    - PYTHON: "C:\\Python312-x64"


install:
  # We need wheel installed to build wheels
  - "%PYTHON%\\python3.exe -m pip install -U pip wheel setuptools"
  - "%PYTHON%\\python3.exe -m pip install pytest"
  - "%PYTHON%\\python3.exe -m pip install -r tests/requirements.txt"
  - "%PYTHON%\\python3.exe -m pip install ."

build: off

test_script:
  - "%PYTHON%\\python3.exe -m pytest"
